<?php
define('SUB_KEYWORD_GET_SERVICE_CODES','get_service_codes');
define('SUB_KEYWORD_SUBMIT_REQUEST','submit_request');
define('SUB_KEYWORD_CHECK_REQUEST_STATUS','check_request_status');
define('SUB_KEYWORD_HELP','help');
define('GROUP_OPTIONS_PREFIX','g');
define('SERVICE_OPTIONS_PREFIX','s');
define('GROUP_LIST_INFO_TEXT','Reply \''.SMS_KEYWORD.'&lt;space&gt;group code\' to receive list of services in that group;Groups:');
define('SERVICE_LIST_INFO_TEXT','Services:');
define('SUCCESSFUL_REQUEST_SUBMISSION_TEXT','Your request has been successfully registered. Your service request id is:');
define('UNSUCCESSFUL_REQUEST_SUBMISSION_TEXT','Your request was not registered. Please Retry');
define('STRING_DATATYPE_RESPONSE_TEXT_1','Additional info required:');
define('STRING_DATATYPE_RESPONSE_TEXT_2','Reply \''.SMS_KEYWORD.'&lt;space&lt;(your answer)\'');
define('NUMBER_DATATYPE_RESPONSE_TEXT_1','Additional info required:');
define('NUMBER_DATATYPE_RESPONSE_TEXT_2','Reply \''.SMS_KEYWORD.'&lt;space&lt;(your answer)\'');
define('DATETIME_DATATYPE_RESPONSE_TEXT_1','Additional info required:');
define('DATETIME_DATATYPE_RESPONSE_TEXT_2','Reply \''.SMS_KEYWORD.'&lt;space&lt;(your answer)\'');
define('TEXT_DATATYPE_RESPONSE_TEXT_1','Additional info required:');
define('TEXT_DATATYPE_RESPONSE_TEXT_2','Reply \''.SMS_KEYWORD.'&lt;space&lt;(your answer)\'');
define('SINGLEVALUELIST_DATATYPE_RESPONSE_TEXT_1','Additional info required:');
define('SINGLEVALUELIST_DATATYPE_RESPONSE_TEXT_2','Reply \''.SMS_KEYWORD.'&lt;space&lt;option code;Options:\'');
define('MULTIVALUELIST_DATATYPE_RESPONSE_TEXT_1','Additional info required:');
define('MULTIVALUELIST_DATATYPE_RESPONSE_TEXT_2','Reply \''.SMS_KEYWORD.'&lt;space&lt;option code;Options:\'');
define('REQUEST_STATUS_RESPONSE_TEXT_1','Request Status:');
define('REQUEST_STATUS_RESPONSE_TEXT_2','Info:');
define('HELP_RESPONSE_TEXT','Reply with \''.SMS_KEYWORD.'&lt;space&lt;option code\' get more details;Options:');
?>
