<h2>SMS Simulator</h2>
<form class="form-horizontal">
	<div class='form-group'>
			<label for="SMSFrom" class="col-lg-2 control-label">From:</label>
			<div class='col-lg-10'>
			<input name="SMSFrom" class="form-control" id="SMSFrom"); ?>
			</div>
      	</div>
	<div class='form-group'>
			<label for="SMSText" class="col-lg-2 control-label">Text:</label>
			<div class='col-lg-10'>
			<input name="SMSText" class="form-control" id="SMSText"); ?>
			</div>
      	</div>

<button id="Submit" class="btn btn-primary">Submit</button>
</form>
<p></p>
<div class="panel">
	<div class="panel-heading">Response:</div>
	<div id="SMSResponse"></div>		
</div>


